name: Deploy to DigitalOcean

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            git fetch origin
            git checkout gh-pages
            git pull origin gh-pages
            sudo /usr/bin/chown -R deploy:www-data /var/www/default-site
            sudo /usr/sbin/nginx -t
            sudo /usr/bin/systemctl reload nginx
